apiVersion: v2
name: self-upgrading-chart
description: A Helm chart for autonomous updates and deployment management
type: application
version: 0.1.0
appVersion: "1.0.0"
kubeVersion: ">=1.19.0-0"

maintainers:
  - name: DevOps Team
    email: devops@example.com

dependencies:
  - name: prometheus
    version: ">=15.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: ">=6.0.0"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
